apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vault
    spec:
      containers:
      - image: vault:1.13.3
        name: vault
        ports:
        - containerPort: 8200
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vault
  name: vault
spec:
  ports:
  - name: 8200-8200
    port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app: vault
  type: NodePort
status:
  loadBalancer: {}
