apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: null
  labels:
    app: lab3
  name: lab3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lab3
    spec:
      containers:
      - image: ifilyaninitmo/itdt-contained-frontend:master
        name: itdt-contained-frontend
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: lab3-configmap
              key: REACT_APP_USERNAME
        - name: REACT_APP_COMPANY_NAME
          valueFrom:
            configMapKeyRef:
              name: lab3-configmap
              key: REACT_APP_COMPANY_NAME
        resources: {}
status: {}
